-- Generated by LuaSTG editor
-- Mod name: unnamed
_author="LuaSTG User"
_mod_version=4096
_allow_practice=true
_allow_sc_practice=true

_editor_class["Boss"]=boss.define("Boss","CAU",240,384,spellcard_background,"All",nil,nil,"cau_bg.jpg",4,4,16,16,8,{4,4,4,4},{1,1,1})
table.insert(_editor_class["Boss"].cards,boss.move.New(0,144,60,MOVE_NORMAL))
_tmp_sc=boss.card.New("SpellCard",2,15,60,600,{0,0,0},false)
function _tmp_sc:init()
    lasttask=task.New(self,function()
        do for _=1,_infinite do
            _create_bullet_group(ball_huge,COLOR_RED,self.x,self.y,5,0,3,4,270,90,false,0,true,true,0,false,self)
            task._Wait(20)
        end end
    end)
end
function _tmp_sc:del()
end
_tmp_sc.perform=false
table.insert(_editor_class["Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"Boss","SpellCard",_tmp_sc,#_editor_class["Boss"].cards,false})
stage.group.New('menu',{},"Spell Card",{lifeleft=7,power=400,faith=50000,bomb=3},true,1)
stage.group.AddStage('Spell Card','Spell Card@Spell Card',{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('Spell Card@Spell Card','init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty    New(mask_fader,'open')
   New(_G[lstg.var.player_name])
    task.New(self,function()
        do
            LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
            New(temple_background)
        end
        task._Wait(60)
        LoadMusicRecord("spellcard");_play_music("spellcard")
        if false then ex.stageframe=0 end
        local _boss_wait=true
        local _ref=boss.createWithCards("Boss",_editor_class["Boss"].cards)
        last=_ref
        if _boss_wait then
            while IsValid(_ref) do
                task.Wait()
            end
        end
        task._Wait(180)
    end)
    task.New(self,function()
		while coroutine.status(self.task[1])~='dead' do task.Wait() end
		stage.group.FinishReplay()
		New(mask_fader,'close')
		task.New(self,function()
			local _,bgm=EnumRes('bgm')
			for i=1,30 do 
				for _,v in pairs(bgm) do
					if GetMusicState(v)=='playing' then
					SetBGMVolume(v,1-i/30) end
				end
				task.Wait()
		end end)
		task.Wait(30)
		stage.group.FinishStage()
	end)
end)
